services:
  springboot-container:
    image: springboo-container
    container_name: springboot-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network:
      - 
     